#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_Mail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="springfield_current")]
	public partial class MailDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsf_Email(sf_Email instance);
    partial void Updatesf_Email(sf_Email instance);
    partial void Deletesf_Email(sf_Email instance);
    #endregion
		
		public MailDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["springfield_currentConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MailDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MailDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sf_Email> sf_Emails
		{
			get
			{
				return this.GetTable<sf_Email>();
			}
		}
		
		public System.Data.Linq.Table<sf_Feedback_back> sf_Feedback_backs
		{
			get
			{
				return this.GetTable<sf_Feedback_back>();
			}
		}
		
		public System.Data.Linq.Table<sf_EmailTemplate> sf_EmailTemplates
		{
			get
			{
				return this.GetTable<sf_EmailTemplate>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sf_GetUncompleteFeedback")]
		public ISingleResult<sf_GetUncompleteFeedbackResult> sf_GetUncompleteFeedback([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="DateTime")] System.Nullable<System.DateTime> dueDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dueDate);
			return ((ISingleResult<sf_GetUncompleteFeedbackResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sf_Email")]
	public partial class sf_Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmailId;
		
		private System.Nullable<int> _Priority;
		
		private System.Nullable<int> _BodyFormat;
		
		private string _From;
		
		private string _To;
		
		private string _Cc;
		
		private string _Bcc;
		
		private string _Subject;
		
		private string _Body;
		
		private System.Nullable<System.DateTime> _NextTryTime;
		
		private System.Nullable<int> _NumberOfTries;
		
		private int _IsSend;
		
		private System.Nullable<System.Guid> _RelatedUserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailIdChanging(int value);
    partial void OnEmailIdChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnBodyFormatChanging(System.Nullable<int> value);
    partial void OnBodyFormatChanged();
    partial void OnFromChanging(string value);
    partial void OnFromChanged();
    partial void OnToChanging(string value);
    partial void OnToChanged();
    partial void OnCcChanging(string value);
    partial void OnCcChanged();
    partial void OnBccChanging(string value);
    partial void OnBccChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnNextTryTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnNextTryTimeChanged();
    partial void OnNumberOfTriesChanging(System.Nullable<int> value);
    partial void OnNumberOfTriesChanged();
    partial void OnIsSendChanging(int value);
    partial void OnIsSendChanged();
    partial void OnRelatedUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnRelatedUserIdChanged();
    #endregion
		
		public sf_Email()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this.OnEmailIdChanging(value);
					this.SendPropertyChanging();
					this._EmailId = value;
					this.SendPropertyChanged("EmailId");
					this.OnEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyFormat", DbType="Int")]
		public System.Nullable<int> BodyFormat
		{
			get
			{
				return this._BodyFormat;
			}
			set
			{
				if ((this._BodyFormat != value))
				{
					this.OnBodyFormatChanging(value);
					this.SendPropertyChanging();
					this._BodyFormat = value;
					this.SendPropertyChanged("BodyFormat");
					this.OnBodyFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[From]", Storage="_From", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string From
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this.OnFromChanging(value);
					this.SendPropertyChanging();
					this._From = value;
					this.SendPropertyChanged("From");
					this.OnFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[To]", Storage="_To", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string To
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this.OnToChanging(value);
					this.SendPropertyChanging();
					this._To = value;
					this.SendPropertyChanged("To");
					this.OnToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cc", DbType="NVarChar(256)")]
		public string Cc
		{
			get
			{
				return this._Cc;
			}
			set
			{
				if ((this._Cc != value))
				{
					this.OnCcChanging(value);
					this.SendPropertyChanging();
					this._Cc = value;
					this.SendPropertyChanged("Cc");
					this.OnCcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bcc", DbType="NVarChar(256)")]
		public string Bcc
		{
			get
			{
				return this._Bcc;
			}
			set
			{
				if ((this._Bcc != value))
				{
					this.OnBccChanging(value);
					this.SendPropertyChanging();
					this._Bcc = value;
					this.SendPropertyChanged("Bcc");
					this.OnBccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NVarChar(MAX)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextTryTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> NextTryTime
		{
			get
			{
				return this._NextTryTime;
			}
			set
			{
				if ((this._NextTryTime != value))
				{
					this.OnNextTryTimeChanging(value);
					this.SendPropertyChanging();
					this._NextTryTime = value;
					this.SendPropertyChanged("NextTryTime");
					this.OnNextTryTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfTries", DbType="Int")]
		public System.Nullable<int> NumberOfTries
		{
			get
			{
				return this._NumberOfTries;
			}
			set
			{
				if ((this._NumberOfTries != value))
				{
					this.OnNumberOfTriesChanging(value);
					this.SendPropertyChanging();
					this._NumberOfTries = value;
					this.SendPropertyChanged("NumberOfTries");
					this.OnNumberOfTriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSend", DbType="Int NOT NULL")]
		public int IsSend
		{
			get
			{
				return this._IsSend;
			}
			set
			{
				if ((this._IsSend != value))
				{
					this.OnIsSendChanging(value);
					this.SendPropertyChanging();
					this._IsSend = value;
					this.SendPropertyChanged("IsSend");
					this.OnIsSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedUserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> RelatedUserId
		{
			get
			{
				return this._RelatedUserId;
			}
			set
			{
				if ((this._RelatedUserId != value))
				{
					this.OnRelatedUserIdChanging(value);
					this.SendPropertyChanging();
					this._RelatedUserId = value;
					this.SendPropertyChanged("RelatedUserId");
					this.OnRelatedUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sf_Feedback_back")]
	public partial class sf_Feedback_back
	{
		
		private int _FeedbackId;
		
		private System.Guid _InterviewerId;
		
		private System.Guid _ApplicantId;
		
		private System.Nullable<int> _InterviewId;
		
		private System.Nullable<int> _SuggestionResult;
		
		private string _FeedbackContent;
		
		private System.Nullable<System.DateTime> _InterviewDate;
		
		private bool _IsComplete;
		
		private System.DateTime _DueDate;
		
		private string _InterviewerAlias;
		
		public sf_Feedback_back()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackId", DbType="Int NOT NULL")]
		public int FeedbackId
		{
			get
			{
				return this._FeedbackId;
			}
			set
			{
				if ((this._FeedbackId != value))
				{
					this._FeedbackId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewerId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid InterviewerId
		{
			get
			{
				return this._InterviewerId;
			}
			set
			{
				if ((this._InterviewerId != value))
				{
					this._InterviewerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicantId
		{
			get
			{
				return this._ApplicantId;
			}
			set
			{
				if ((this._ApplicantId != value))
				{
					this._ApplicantId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewId", DbType="Int")]
		public System.Nullable<int> InterviewId
		{
			get
			{
				return this._InterviewId;
			}
			set
			{
				if ((this._InterviewId != value))
				{
					this._InterviewId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuggestionResult", DbType="Int")]
		public System.Nullable<int> SuggestionResult
		{
			get
			{
				return this._SuggestionResult;
			}
			set
			{
				if ((this._SuggestionResult != value))
				{
					this._SuggestionResult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackContent", DbType="NVarChar(4000)")]
		public string FeedbackContent
		{
			get
			{
				return this._FeedbackContent;
			}
			set
			{
				if ((this._FeedbackContent != value))
				{
					this._FeedbackContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InterviewDate
		{
			get
			{
				return this._InterviewDate;
			}
			set
			{
				if ((this._InterviewDate != value))
				{
					this._InterviewDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit NOT NULL")]
		public bool IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this._IsComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime NOT NULL")]
		public System.DateTime DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this._DueDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewerAlias", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string InterviewerAlias
		{
			get
			{
				return this._InterviewerAlias;
			}
			set
			{
				if ((this._InterviewerAlias != value))
				{
					this._InterviewerAlias = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sf_EmailTemplate")]
	public partial class sf_EmailTemplate
	{
		
		private int _EmailType;
		
		private string _EmailTemplate;
		
		private string _EmailSubject;
		
		private string _EmailFrom;
		
		private string _EmailTo;
		
		private string _EmailCc;
		
		private string _EmailBcc;
		
		public sf_EmailTemplate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailType", DbType="Int NOT NULL")]
		public int EmailType
		{
			get
			{
				return this._EmailType;
			}
			set
			{
				if ((this._EmailType != value))
				{
					this._EmailType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplate", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailTemplate
		{
			get
			{
				return this._EmailTemplate;
			}
			set
			{
				if ((this._EmailTemplate != value))
				{
					this._EmailTemplate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="NVarChar(256)")]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFrom", DbType="NVarChar(256)")]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this._EmailFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTo", DbType="NVarChar(256)")]
		public string EmailTo
		{
			get
			{
				return this._EmailTo;
			}
			set
			{
				if ((this._EmailTo != value))
				{
					this._EmailTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCc", DbType="NVarChar(256)")]
		public string EmailCc
		{
			get
			{
				return this._EmailCc;
			}
			set
			{
				if ((this._EmailCc != value))
				{
					this._EmailCc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBcc", DbType="NVarChar(256)")]
		public string EmailBcc
		{
			get
			{
				return this._EmailBcc;
			}
			set
			{
				if ((this._EmailBcc != value))
				{
					this._EmailBcc = value;
				}
			}
		}
	}
	
	public partial class sf_GetUncompleteFeedbackResult
	{
		
		private System.Guid _applicantid;
		
		private string _InterviewerAlias;
		
		private string _UserName;
		
		private int _FeedbackId;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _NameInChinese;
		
		private System.DateTime _DueDate;
		
		public sf_GetUncompleteFeedbackResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicantid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid applicantid
		{
			get
			{
				return this._applicantid;
			}
			set
			{
				if ((this._applicantid != value))
				{
					this._applicantid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterviewerAlias", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string InterviewerAlias
		{
			get
			{
				return this._InterviewerAlias;
			}
			set
			{
				if ((this._InterviewerAlias != value))
				{
					this._InterviewerAlias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackId", DbType="Int NOT NULL")]
		public int FeedbackId
		{
			get
			{
				return this._FeedbackId;
			}
			set
			{
				if ((this._FeedbackId != value))
				{
					this._FeedbackId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameInChinese", DbType="NVarChar(256)")]
		public string NameInChinese
		{
			get
			{
				return this._NameInChinese;
			}
			set
			{
				if ((this._NameInChinese != value))
				{
					this._NameInChinese = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime NOT NULL")]
		public System.DateTime DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this._DueDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
